### ISSUE TITLE
Doesn't move forward

### ISSUE THREAD

**Issue by nicknikolov** [Bienoise/Skip#1]
Hey, thanks for making this device! I am struggling to making it move forward though. Playing C3 makes a sound but the timer is stuck on 00:00:00. Any ideas? I am on Live 11, MacOS. 

Thanks!

**Comment by Bienoise** [comment]
Ehi! Thank you for using it!
It could be a couple of reasons:
- sometimes, in particular when loading Mp3 files that Live hasn't analyzed yet, you need to drop it a second time to make the interface work properly.
- if the duration of your sound is shorter than the Skip Time, it may appear as you describe. Try making the Skip Time shorter to see if this is the problem!

Best
A

**Comment by nicknikolov** [comment]
Whoops, of course. My samples were too short! Thank you.
